priorities_subject = {
    "1girl": 100,
    "2girls": 100,
    "multiple_girls": 100,
    "1boy": 100,
    "2boys": 100,
    "3boys": 100,
    "4boys": 100,
    "multiple_boys": 100,
    "hetero": 100,
    "solo_focus": 100,
    "solo": 100,
    "sex": 100,
    "pov": 100,
    "threesome": 100,
    "close-up": 100,
    "clothed_female_nude_male": 100,
    "clothed_male_nude_female": 100,
    "group_sex": 100,
    "mmf_threesome": 100,
    "ffm_threesome": 100,
    "bdsm": 100,
    "ass_focus": 100,
}

priorities_pose = {
    "missionary": 90,
    "fellatio": 90,
    "oral": 90,
    "spread_legs": 90,
    "double_handjob": 90,
    "double_penetration": 90,
    "all_fours": 90,
    "vaginal": 90,
    "looking_at_viewer": 90,
    "looking_back": 90,
    "lying": 90,
    "bow": 90,
    "girl_on_top": 90,
    "straddling": 90,
    "cowgirl_position": 90,
    "reverse_cowgirl_position": 90,
    "squatting_cowgirl_position": 90,
    "doggystyle": 90,
    "after_sex": 90,
    "on_back": 90,
    "sex_from_behind": 90,
    "sitting": 90,
    "kiss": 90,
    "licking": 90,
    "licking_penis": 90,
    "licking_nipple": 90,
    "grabbing": 90,
    "grabbing_own_breast": 90,
    "arms_up": 90,
    "breast_grab": 90,
    "ass_grab": 90,
    "clothes_lift": 90,
    "skirt_lift": 90,
    "shirt_lift": 90,
    "squatting": 90,
    "pov_crotch": 90,
    "open_clothes": 90,
    "bend_over": 90,
    "fingering": 90,
    "nipple_tweak": 90,
    "erection": 90,
    "handjob": 90,
    "kneeling": 90,
    "bound": 90,
    "standing": 90,
    "from_behind": 90,
    "from_below": 90,
    "masturbation": 90,
    "paizuri": 90,
    "cunnilingus": 90,
    "female_masturbation": 90,
    "sleeping": 90,
}

priorities_cum = {
    "cum": 80,
    "cumdrip": 80,
    "ejaculation": 80,
    "facial": 80,
    "saliva": 80,
    "sweat": 80,
    "pussy_juice": 80,
    "cum_on_body": 80,
    "cum_on_brests": 80,
    "cum_on_legs": 80,
    "cum_on_hair": 80,
    "cum_on_ass": 80,
    "cum_in_ass": 80,
    "cum_on_stomach": 80,
    "cum_on_clothes": 80,
    "cum_on_feet": 80,
    "cum_on_hands": 80,
    "cum_on_tongue": 80,
    "cum_in_pussy": 80,
    "cum_in_mouth": 80,
}

priorities_clothes = {
    "completely_nude": 70,
    "underwear_only": 70,
    "nude": 70,
    "shirt": 70,
    "glasses": 70,
    "white_shirt": 70,
    "serafuku": 70,
    "bikini": 70,
    "swimsuit": 70,
    "lingerie": 70,
    "underwear": 70,
    "panties": 70,
    "pantyhose": 70,
    "white_panties": 70,
    "bra": 70,
    "skirt": 70,
    "socks": 70,
    "school_uniform": 70,
    "jewelry": 70,
    "thighhighs": 70,
    "bottomless": 70,
    "topless": 70,
    "vibrator": 70,
    "clothing_aside": 70,
    "panties_aside": 70,
    "bondage": 70,
    "no_panties": 70,
}

priorities_body_parts = {
    "black_hair": 60,
    "brown_hair": 60,
    "blonde_hair": 60,
    "wavy_hair": 60,
    "very_long_hair": 60,
    "long_hair": 60,
    "short_hair": 60,
    "medium_hair": 60,
    "bangs": 60,
    "nose": 60,
    "black_eyes": 60,
    "brown_eyes": 60,
    "teeth": 60,
    "tongue": 60,
    "lips": 60,
    "breasts": 60,
    "upper_body": 60,
    "large_breasts": 60,
    "medium_breasts": 60,
    "small_breasts": 60,
    "flat_chest": 60,
    "nipples": 60,
    "navel": 60,
    "cleavage": 60,
    "penis": 60,
    "multiple_penises": 60,
    "pussy": 60,
    "ass": 60,
    "anus": 60,
    "pubic_hair": 60,
    "female_pubic_hair": 60,
    "male_pubic_hair": 60,
    "feet": 60,
    "thighs": 60,
    "barefoot": 60,
    "mole": 60,
}

priorities_face_expression = {
    "smile": 50,
    "grin": 50,
    "closed_eyes": 50,
    "closed_mouth": 50,
    "tongue_out": 50,
    "open_mouth": 50,
    "parted_lips": 50,
}

priorities_background = {
    "indoors": 40,
    "outdoors": 40,
    "bed": 40,
    "plant": 40,
    "on_bed": 40,
    "pillow": 40,
    "couch": 40,
}

priorities_effect = {
    "depth_of_field": 30,
    "bokeh": 30,
    "blurry": 30,
    "blurry_background": 30,
    "vignette": 30,
    "censored": 30,
    "mosaic_censoring": 30,
}

priorities = {
    **priorities_subject,
    **priorities_pose,
    **priorities_cum,
    **priorities_clothes,
    **priorities_body_parts,
    **priorities_background,
    **priorities_effect,
}


def priorities_key(tag: str) -> int:
    if tag in priorities:
        return priorities[tag]
    return 0


def reorder_tags(tags: list[str]) -> list[str]:
    tags.sort(key=priorities_key, reverse=True)
    return tags


if __name__ == "__main__":
    result = reorder_tags(["1girl", "facial", "bokeh", "outdoors", "1boy", "swimsuit"])
    print(result)
